export const statesByClass = {
    sm_state_HI: 'Hawaii',
    sm_state_AK: 'Alaska',
    sm_state_FL: 'Florida',
    sm_state_NH: 'New Hampshire',
    sm_state_VT: 'Vermont',
    sm_state_ME: 'Maine',
    sm_state_RI: 'Rhode Island',
    sm_state_NY: 'New York',
    sm_state_PA: 'Pennsylvania',
    sm_state_NJ: 'New Jersey',
    sm_state_DE: 'Delaware',
    sm_state_MD: 'Maryland',
    sm_state_VA: 'Virginia',
    sm_state_WV: 'West Verginia',
    sm_state_OH: 'Ohio',
    sm_state_IN: 'Indiana',
    sm_state_IL: 'Illinois',
    sm_state_CT: 'Connecticut',
    sm_state_WI: 'Wisconsin',
    sm_state_NC: 'North Carolina',
    sm_state_MA: 'Massachusetts',
    sm_state_TN: 'Tennessee',
    sm_state_AR: 'Arkansas',
    sm_state_MO: 'Missouri',
    sm_state_GA: 'Georgia',
    sm_state_SC: 'South Carolina',
    sm_state_KY: 'Kentucky',
    sm_state_AL: 'Alabama',
    sm_state_LA: 'Louisiana',
    sm_state_MS: 'Mississippi',
    sm_state_IA: 'Iowa',
    sm_state_MN: 'Minnesota',
    sm_state_OK: 'Oklahoma',
    sm_state_TX: 'Texas',
    sm_state_NM: 'New Mexico',
    sm_state_KS: 'Kansas',
    sm_state_NE: 'Nebraska',
    sm_state_SD: 'South Dakota',
    sm_state_ND: 'North Dakota',
    sm_state_WY: 'Wyoming',
    sm_state_MT: 'Montana',
    sm_state_CO: 'Colorado',
    sm_state_UT: 'Utah',
    sm_state_AZ: 'Arizona',
    sm_state_NV: 'Nevada',
    sm_state_OR: 'Oregon',
    sm_state_WA: 'Washington',
    sm_state_CA: 'California',
    sm_state_MI: 'Michigan',
    sm_state_ID: 'Idaho'
}

export const statesByClassAbreviation = {
    sm_state_HI: 'HI',
    sm_state_AK: 'AK',
    sm_state_FL: 'FL',
    sm_state_NH: 'NH',
    sm_state_VT: 'VT',
    sm_state_ME: 'ME',
    sm_state_RI: 'RI',
    sm_state_NY: 'NY',
    sm_state_PA: 'PA',
    sm_state_NJ: 'NJ',
    sm_state_DE: 'DE',
    sm_state_MD: 'MD',
    sm_state_VA: 'VA',
    sm_state_WV: 'WV',
    sm_state_OH: 'OH',
    sm_state_IN: 'IN',
    sm_state_IL: 'IL',
    sm_state_CT: 'CT',
    sm_state_WI: 'WI',
    sm_state_NC: 'NC',
    sm_state_MA: 'MA',
    sm_state_TN: 'TN',
    sm_state_AR: 'AR',
    sm_state_MO: 'MO',
    sm_state_GA: 'GA',
    sm_state_SC: 'SC',
    sm_state_KY: 'KY',
    sm_state_AL: 'AL',
    sm_state_LA: 'LA',
    sm_state_MS: 'MS',
    sm_state_IA: 'IA',
    sm_state_MN: 'MN',
    sm_state_OK: 'OK',
    sm_state_TX: 'TX',
    sm_state_NM: 'NM',
    sm_state_KS: 'KN',
    sm_state_NE: 'NE',
    sm_state_SD: 'SD',
    sm_state_ND: 'ND',
    sm_state_WY: 'WY',
    sm_state_MT: 'MT',
    sm_state_CO: 'CO',
    sm_state_UT: 'UT',
    sm_state_AZ: 'AZ',
    sm_state_NV: 'NA',
    sm_state_OR: 'OR',
    sm_state_WA: 'WA',
    sm_state_CA: 'CA',
    sm_state_MI: 'MI',
    sm_state_ID: 'ID'
}